[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =  lvgl/lvgl @ ^8.3.11
            lvgl/lv_drivers @ ^8.2.0

[env:test_scheduler]
platform=native
test_filter=test_scheduler
test_build_src = yes
build_src_filter =
    -<**/*>
    +<Scheduler.cpp>
    +<StringParser.cpp>
    +<ObdParser.cpp>
    +<DataStorage.cpp>
    +<PidManager.cpp>

[env:test_elm_controller]
platform = native
test_filter = test_elm_controller
test_build_src = yes
build_src_filter =
    -<**/*>
    +<Elm327Controller.cpp>


[env:test_pid_manager]
platform = native
test_filter = test_pid_manager
test_build_src = yes
build_src_filter =
    -<**/*>
    +<PidManager.cpp>
    +<DataStorage.cpp>
    +<ObdParser.cpp>

[env:test_string_parser]
platform = native
test_filter = test_string_parser
test_build_src = yes
build_src_filter =
    -<**/*>
    +<StringParser.cpp>

[env:test_obd_parser]
platform=native
test_filter = test_obd_parser
test_build_src = yes
build_src_filter =
    -<**/*>
    +<ObdParser.cpp>

[env:native]
platform = native
test_build_src = yes
build_src_filter =
    +<*>
    -<UI/>
    -<Elm327Controller.cpp>
    -<main.cpp>
build_flags = -D UNIT_TEST

[env:integration_test]
platform = native
test_filter =test_integration
test_build_src = yes
build_src_filter =
    +<**/*>
    -<UI/>
    -<main.cpp>
    -<BluetoothHandler.cpp>
    -<mock/>


[env:emulator]
platform = native
build_flags =
    -I include
    -lSDL2
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_DRV_CONF_INCLUDE_SIMPLE
    -D SDL_MAIN_HANDLED
    -D USE_MOCK_BLUETOOTH
build_src_filter =
    +<**/*>
    -<BluetoothHandler.cpp>
    +<../mock/MockBluetoothHandler.cpp>
lib_deps =
    lvgl/lvgl @ ^8.3.11
    lvgl/lv_drivers @ ^8.2.0