//
// Created by User on 1/7/2026.
//

#ifndef OBD_AUTOMOTIVE_DISPLAY_COMUNICATIONSTATES_H
#define OBD_AUTOMOTIVE_DISPLAY_COMUNICATIONSTATES_H
enum class State{
    CONNECTING,
    IDLE,
    SEND_REQUEST,
    WAIT_REPLY,
    PARSE_REPLY,
    ERROR,
    DISCONNECTED,
};

#endif //OBD_AUTOMOTIVE_DISPLAY_COMUNICATIONSTATES_H
